In [1]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import itertools

In [2]:
df1_path='img/data/tracks_by_year_top_ssoc1.csv'
df2_path='img/data/tracks_by_year_top_ssoc2.csv'
df3_path='img/data/tracks_by_year_top_ssoc3.csv'
df1=pd.read_csv(df1_path)
df2=pd.read_csv(df2_path)
df3=pd.read_csv(df3_path)

In [3]:
df1

     ssoc4d    tracks_final  year  JOB_POST_ID  scaled_JOB_POST_ID
0      1120            data  2018         1336                5344
1      1120            data  2019         4490                4490
2      1120            data  2020         2602                2602
3      1120            data  2021         1507                4521
4      1120  infrastructure  2018         1998                7992
..      ...             ...   ...          ...                 ...
115    1412        software  2021         2159                6477
116    1412         support  2018         1030                4120
117    1412         support  2019         3423                3423
118    1412         support  2020         1709                1709
119    1412         support  2021         1621                4863

[120 rows x 5 columns]

In [89]:
dflist=[df1,df2,df3]
for idx, df in enumerate(dflist):
    df['year']=df['year'].apply(str)

    sns.set_style('whitegrid')

    fig, axs = plt.subplots(1, 5,figsize=(17,4))
    ssoclist=df['ssoc4d'].unique().tolist()
    tracklist=df['tracks_final'].unique().tolist()

    g1=sns.lineplot(data=df[df['ssoc4d']==ssoclist[0]], x='year', y='scaled_JOB_POST_ID', hue='tracks_final', palette='Set2',ax=axs[0])
    g2=sns.lineplot(data=df[df['ssoc4d']==ssoclist[1]], x='year', y='scaled_JOB_POST_ID', hue='tracks_final', palette='Set2',ax=axs[1])
    g3=sns.lineplot(data=df[df['ssoc4d']==ssoclist[2]], x='year', y='scaled_JOB_POST_ID', hue='tracks_final', palette='Set2',ax=axs[2])
    g4=sns.lineplot(data=df[df['ssoc4d']==ssoclist[3]], x='year', y='scaled_JOB_POST_ID', hue='tracks_final', palette='Set2',ax=axs[3])
    g5=sns.lineplot(data=df[df['ssoc4d']==ssoclist[4]], x='year', y='scaled_JOB_POST_ID', hue='tracks_final', palette='Set2',ax=axs[4])

    g1.get_legend().remove()
    g2.get_legend().remove()
    g3.get_legend().remove()
    g4.get_legend().remove()
    g5.get_legend().remove()

    for i,ssoc in enumerate(ssoclist):
        axs[i].set_title('SSOC4D '+str(ssoclist[i]))
        sns.despine(top=True, right=True,left=True)

        if idx==0:
            axs[i].set_ylim(0,25000)
        elif idx==1:
            axs[i].set_ylim(0,30000)
        else:
            axs[i].set_ylim(0,25000)
            

        if i==2:
            axs[i].set_xlabel("Year")
        else:
            axs[i].set_xlabel("")

        if i==0:
            axs[i].set_ylabel("Number of job postings")
        else:
            axs[i].set_ylabel('')

    fig.suptitle('Number of job postings requiring each digital skill main track for SSOC Group {}'.format(str(idx+1)))

    axs.flatten()[-2].legend(title='Main track',loc='center left', bbox_to_anchor=(2.2, 0.5), ncol=1)
    plt.tight_layout()
    plt.savefig('img/top_ssoc{}_tracks_by_year.png'.format(str(idx+1)))
    plt.close()

<ipython-input-89-3a70e996bfef>:48: UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations
  plt.tight_layout()
<ipython-input-89-3a70e996bfef>:48: UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations
  plt.tight_layout()
<ipython-input-89-3a70e996bfef>:48: UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations
  plt.tight_layout()

In [15]:
df1

     ssoc4d    tracks_final  year  JOB_POST_ID  scaled_JOB_POST_ID
0      1120            data  2018         1336                5344
1      1120            data  2019         4490                4490
2      1120            data  2020         2602                2602
3      1120            data  2021         1507                4521
4      1120  infrastructure  2018         1998                7992
..      ...             ...   ...          ...                 ...
115    1412        software  2021         2159                6477
116    1412         support  2018         1030                4120
117    1412         support  2019         3423                3423
118    1412         support  2020         1709                1709
119    1412         support  2021         1621                4863

[120 rows x 5 columns]

In [35]:
# delta

df=df1.append(df2).append(df3)
df["rank"] = df.groupby(['ssoc4d','year'])['scaled_JOB_POST_ID'].rank("dense", ascending=False)
df=df[df['year'].isin([2018,2021])]
df.sort_values(by=['ssoc4d','tracks_final','year'],inplace=True)
df['rankdelta']=df[['rank']].diff() # change in ranking from 2018 to 2021 (negative means rise in ranks)
df=df[df['year']==2021]
df

,ssoc4d,tracks_final,year,JOB_POST_ID,scaled_JOB_POST_ID,rank,rankdelta
15,1120,cybersecurity,2021,1005,3015,6.0,NaN
3,1120,data,2021,1507,4521,5.0,-1.0
7,1120,infrastructure,2021,2390,7170,3.0,-2.0
19,1120,software,2021,2670,8010,1.0,-2.0
11,1120,strategy,2021,2669,8007,2.0,1.0
...,...,...,...,...,...,...,...
99,3999,data,2021,1567,4701,5.0,0.0
103,3999,infrastructure,2021,2619,7857,2.0,-1.0
115,3999,software,2021,2774,8322,1.0,0.0
107,3999,strategy,2021,2435,7305,3.0,1.0
119,3999,support,2021,2426,7278,4.0,0.0

In [37]:
print(df.groupby(['tracks_final'])['rankdelta'].sum())

tracks_final
cybersecurity      9.0
data              -5.0
infrastructure   -11.0
software          -8.0
strategy          13.0
support            0.0
Name: rankdelta, dtype: float64